FROM python:3.12.2-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install wget and other necessary packages
RUN apt-get update && apt-get install -y gcc g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN python3 -m ensurepip && \
    python3 -m pip install --no-cache-dir -r requirements.txt

RUN pip3 install llama-cpp-python==0.2.56 --no-cache-dir --force-reinstall --upgrade

EXPOSE 8501

CMD ["streamlit", "run", "app_qa.py", "--server.address=0.0.0.0"]